### PR TITLE
[gitlab] option to change base-url for gitlab

### PR DESCRIPTION
**Pull request by mareksimunek**
Did I miss some flag or it's not possible to change baseurl for gitlab?

My usecase is to change it to gitlab url which we have as company self-managed

### CODE REVIEW

**Comment by mareksimunek** [comment]
@lindell

**Comment by lindell** [comment]
Thanks for the PR. I've never worked with self hosted GitLab and had no way of testing it. This should be merged, but we first need to fix the long version of the flag name `gh-base-url`. I think it would be fine to break backward compatibility now (since it's beta) and use `base-url`. What do you think? :) 

PS. No need to change in the readme as that will automatically be generated once this is merged ;)

**Review by lindell — APPROVED** [review]
LGTM 🙂

**Comment by mareksimunek** [comment]
I thank you very much for the project, as for the flag I agree. I was afraid of breaking backward compatibility, but if its ok. I all for it.

Add readme: that's great.  I was thinking that it would be pain to maintain it :D

**Comment by lindell** [comment]
I'm just glad this is starting to get used since I have saved countless hours using it myself already :D 

It's very handy to keep these things easy to maintain, otherwise, you quickly get tired of keeping OS projects running ;)

**Comment by lindell** [comment]
This is now released in: https://github.com/lindell/multi-gitter/releases/tag/v0.20.0

**Comment by mareksimunek** [comment]
> This is now released in: https://github.com/lindell/multi-gitter/releases/tag/v0.20.0

thanks, for the quick reactions :)

**Pull request merged**
