### PR TITLE
fix(gitlab): only list projects with Merge Requests enabled

### PR DESCRIPTION
**Pull request by tmeijn**

### CODE REVIEW

**Comment by tmeijn** [comment]
add comma

**Comment by lindell** [comment]
It looks like the option is a pointer. If you create a variable `withMergeRequestsEnabled := true` you can then refer to it with `WithMergeRequestsEnabled: &withMergeRequestsEnabled`

**Comment by tmeijn** [comment]
Thanks my dude! Really need to start learning Go.

**Review by lindell — APPROVED** [review]
LGTM 👍  Thanks for the contribution.

**Comment by lindell** [comment]
Added to [v0.33.1](https://github.com/lindell/multi-gitter/releases/tag/v0.33.1) 🙂

**Pull request merged**
