### PR TITLE
Config option pr title tag

### PR DESCRIPTION
**Pull request by ismith**
# What does this change

Config option pr-title-tags

A list of tags to prefix a pr-title.

# What issue does it fix

Use case: I'd like to be able to filter PRs created by this tool out of
my email inbox. I can do that by having my team's config contain:
```yaml
pr-title-tags:
  - automated-pr
```

# Notes for the reviewer
`TestPrint` fails for me locally on two asserts (`"i like apples\ni like my apple\ni like oranges\n"` and `"I LIKE APPLES\nI LIKE MY APPLE\nI LIKE ORANGES\n"`), but these also fail on head of master, so I suspect this is a local issue and :crossed_fingers: won't happen in CI.

# Checklist
- [x] Made sure the PR follows the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines
- [x] Tests if something new is added

### CODE REVIEW

**Review by lindell — COMMENTED** [review]
Hello and thanks for the PR 🙂 

The code looks good, but I'm a bit torn on the actual addition. I see the use-case, but it also feels like this is a solution to a problem that may be solved outside of this tool.

Could you please describe exactly how you intend to use this flag/option for me to get a better understanding? Are people in your team using this tool, causing your mailbox to get spammed, and you intend to force them to add the tags to their config? Or are you using multi-gitter in a CI/CD or similar?
The main question I'm trying to get answered is that, in any of these cases, or any other scenario, why can't the tags be added to the title directly?

----

Also, what environment did you run the tests on that made them fail?

**Comment by ismith** [comment]
> Are people in your team using this tool, causing your mailbox to get spammed, and you intend to force them to add the tags to their config?

Yes, this - I want notifications for PRs in my org, but most things done with multi-gitter are (a) not done by my team, and (b) owned in whole by the team using multi-gitter.

> The main question I'm trying to get answered is that, in any of these cases, or any other scenario, why can't the tags be added to the title directly?

In theory it could, and the other team offered to do that - but I'd like this to be a thing that doesn't depend on whether an individual human remembered this step in their workflow on a particular day.  Another not-in-multi-gitter would be a wrapper script in bash or what have you, but ... that seems like the wrong place.)

(The team that uses this tool manages our OSS repos, so it's often used for things like "sunset a bunch of projects at once", CoC updates, etc.)

**Comment by ismith** [comment]
> Also, what environment did you run the tests on that made them fail?

Local ubuntu 20.04, go v1.16.x

**Comment by lindell** [comment]
> In theory it could, and the other team offered to do that - but I'd like this to be a thing that doesn't depend on whether an individual human remembered this step in their workflow on a particular day.

I absolutely agree that removing human error is the best option if possible.

I've tried to find good solutions for this outside of MG, but the only one that is not a wrapper script is to use a bot/automated user instead, which would have benefits in it being even more clear that it was an automated pr/commit, but it may also not be feasible for your org.

Otherwise I'm ok with adding a "things before the PR title" feature, but I think it should be `pr-title-prefix` instead since it's a superset of the tags feature. If anyone want's to have the prefix as `Automated 🤖` or `(tag-with-parentheses)` that should also be possible and should not be two additional options.


> Local ubuntu 20.04, go v1.16.x

20.04.3 is both what I'm running locally and what the CI is running on 🤔 I need to take a further look at this.

**Pull request closed without merging**
