### PR TITLE
ci: reduce Github Action permissions

### PR DESCRIPTION
**Pull request by gustavkj**
# What does this change

Reduces permissions for the Github Actions in the two workflows that had yet to get explicit permissions set.

I'm not entirely sure what permissions Coveralls require, it seems they have not documented it. So, we can see if it runs fine with the given permissions or not. _Update: It was successful and uploaded the coverage._ 👍 

For the release workflow, I think the permissions are enough. But it was not completely documented for the commenter action. From what I can see in the [source code](https://github.com/apexskier/github-release-commenter), the Github calls are: lists releases (`contents: read`), compare commits (`contents: read`), comments and labels on linked issues/prs (`issues: write` and `pull-requests: write`), there's also a graphql query that I think should fly with the other permissions.

# What issue does it fix

This is a continuation on: https://github.com/lindell/multi-gitter/pull/410

### CODE REVIEW

**Comment by lindell** [comment]
`issues: write` will probably be necessary for the commenter action?

**Comment by gustavkj** [comment]
> `issues: write` will probably be necessary for the commenter action?

I just came to that conclusion as well 😅 👍

**Review by lindell — APPROVED** [review]
LGTM 👍 
I think these should be sufficient.

The current changes only includes dependency updates, so could be a good try run to trigger a release directly?

**Comment by gustavkj** [comment]
Sounds good! Do you want to merge?

**Comment by lindell** [comment]
Feel free to do it yourself after approval :)  But can do it now and trigger the release to see the results.

**Comment by lindell** [comment]
Seems to have worked 😄

**Comment by gustavkj** [comment]
Awesome! 😊 🎉

**Pull request merged**
